In [1]:
import pandas as pd
import scanpy as sc

In [2]:
_sample = "sample"
_count_type = "count_type"
_tissue = "tissue"
_disease = "disease"
_technology = "technology"
_project_id = "project_id"
_technologies = ("10X", "SmartSeq2")
_suspension = "suspension"
_suspension_types = ("cell", "nucleus")

In [3]:
def clean_adata(adata: sc.AnnData) -> sc.AnnData:
    for key in list(adata.obsm_keys()):
        del adata.obsm[key]
    for key in list(adata.obsp.keys()):
        del adata.obsp[key]
    
    return adata

In [4]:
metadata = pd.read_csv("study_overview.csv", index_col=0)

## GBM Extend Atlas

In [10]:
url = "https://docs.google.com/spreadsheets/d/1bndaTtNhQe5gPzfEhmeNW_BYSW6m6cF7s4CR-XTDBh4/gviz/tq?tqx=out:csv&sheet=Overview"
metadata = pd.read_csv(url, index_col=0)
metadata = metadata[(metadata["Source"] == "CellxGene(Ruiz)") & (metadata["Include"] == "Yes")]
metadata["name"] = metadata["author_last_name"] + metadata["year"].astype(str)

In [11]:
metadata

,Tissue,Article,Disease,Technology,N_samples,Source,author_last_name,year,Project ID,Include,Reason,name
Spalte 1,,,,,,,,,,,,
Zhao_2020_brain,brain,10.1186/s13073-021-00894-y,GBM,Microwell,1.0,CellxGene(Ruiz),Zhao,2020,CG-4,Yes,NaN,Zhao2020
Wang_2020_brain,brain,10.1016/j.stemcr.2020.01.007,GBM,10x 3',3.0,CellxGene(Ruiz),Wang,2020,CG-5,Yes,NaN,Wang2020
Bhaduri_2020_brain,brain,10.1016/j.stem.2019.11.015,GBM,10x 3',5.0,CellxGene(Ruiz),Bhaduri,2020,CG-7,Yes,NaN,Bhaduri2020
Yu_2020_brain,brain,10.1093/nsr/nwaa099,GBM,Single-cell tagged reverse transcription–seq p...,9.0,CellxGene(Ruiz),Yu,2020,CG-8,Yes,NaN,Yu2020
Wu_2020_brain,brain,10.3389/fonc.2020.566599,GBM,BD Rhapsody,4.0,CellxGene(Ruiz),Wu,2020,CG-9,Yes,NaN,Wu2020
Richards_2021_brain,brain,10.1038/s43018-020-00154-9,GBM,10x 3',7.0,CellxGene(Ruiz),Richards,2021,CG-10,Yes,NaN,Richards2021
Johnson_2020_brain,brain,10.1038/s41588-021-00926-8,GBM,10x 3',5.0,CellxGene(Ruiz),Johnson,2020,CG-11,Yes,NaN,Johnson2020
Pombo_2021_brain,brain,10.1038/s41593-020-00789-y,GBM,10x 3'/10x 5',13.0,CellxGene(Ruiz),Pombo,2021,CG-16,Yes,NaN,Pombo2021
Jacob_2020_brain,brain,10.1016/j.cell.2019.11.036,GBM,Drop-seq,3.0,CellxGene(Ruiz),Jacob,2020,CG-18,Yes,NaN,Jacob2020
Wang_2021_brain,brain,10.1016/j.ccell.2021.01.006,GBM,10x 3',18.0,CellxGene(Ruiz),Wang,2021,CG-19,Yes,NaN,Wang2021
Lee_2021_brain,brain,10.1038/s41467-021-26940-2,GBM,10x 3',35.0,CellxGene(Ruiz),Lee,2021,CG-22,Yes,NaN,Lee2021
Chen_2021_brain,brain,10.1186/s13073-021-00906-x,GBM,Microwell,5.0,CellxGene(Ruiz),Chen,2021,CG-23,Yes,NaN,Chen2021
Abdelfattah_2022_brain,brain,10.1038/s41467-022-28372-y,GBM,10x 3',16.0,CellxGene(Ruiz),Abdelfattah,2022,CG-24,Yes,NaN,Abdelfattah2022
Ravi_2022_brain,brain,10.1038/s41467-022-28523-1,GBM,10x 3',7.0,CellxGene(Ruiz),Ravi,2022,CG-25,Yes,NaN,Ravi2022
LeBlanc_2022_brain,brain,10.1016/j.ccell.2022.02.016,GBM,10x 3',10.0,CellxGene(Ruiz),LeBlanc,2022,CG-26,Yes,NaN,LeBlanc2022
Ruiz_2022_brain,brain,https://www.biorxiv.org/content/10.1101/2022.0...,GBM,10x 3',11.0,CellxGene(Ruiz),Ruiz,2022,CG-27,Yes,NaN,Ruiz2022

In [12]:
adata = sc.read(".cache/ruiz.h5ad", backed="r",backup_url="https://datasets.cellxgene.cziscience.com/d36a23ec-65f6-446e-8e69-c72ccbd44d9e.h5ad")
adata = adata[(adata.obs["cell_type"]=="malignant cell") & (adata.obs["author"].isin(metadata["name"]))]
adata = adata.raw.to_adata()

In [13]:
adata = clean_adata(adata)

In [14]:
adata

AnnData object with n_obs × n_vars = 332314 × 26302
    obs: 'author', 'donor_id', 'assay_ontology_term_id', 'cell_type_ontology_term_id', 'development_stage_ontology_term_id', 'disease_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'is_primary_data', 'organism_ontology_term_id', 'sex_ontology_term_id', 'annotation_level_1', 'annotation_level_2', 'annotation_level_3', 'gbmap', 'method', 'stage', 'location', 'sector', 'celltype_original', 'EGFR', 'MET', 'p53', 'TERT', 'ATRX', 'PTEN', 'MGMT', 'chr1p19q', 'PDGFR', 'suspension_type', 'tissue_ontology_term_id', 'tissue_type', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'feature_types', 'genome', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'X_approximate_distribution', 'batch_condition', 'citation', 'default_embedding', 'hvg', 'schema_reference', 'schema_version', 'title'

In [15]:
#del adata.obsm["X_umap"]
adata.var_names = adata.var["feature_name"].astype(str)
adata.uns = {}

In [24]:
sample_counts = {}
for idx, row in metadata.iterrows():
    bdata = adata[adata.obs["author"]==row["name"]].copy()
    if bdata.n_obs < 100:
        print(study)
        continue
    bdata.var = bdata.var.drop(bdata.var.columns, axis=1)
    bdata.obs = bdata.obs[["donor_id", "assay"]]
    bdata.obs = bdata.obs.rename(columns={"donor_id": _sample, "assay": _technology})
    bdata.obs[_tissue] = "brain"
    bdata.obs[_suspension] = "cell"
    bdata.obs[_project_id] = row["Project ID"]
    bdata.uns = {_count_type: "raw_counts"}
    bdata.write_h5ad(f"data/cellxgene/{idx}.h5ad")

In [20]:
bdata

AnnData object with n_obs × n_vars = 11727 × 26302
    obs: 'sample', 'technology', 'tissue', 'suspension_type', 'project_id'
    uns: 'count_type'

## Breast Cancer CellxGene dataset

In [34]:
adatas = []
for s_type, url in zip(["cell", "nucleus"], ["https://datasets.cellxgene.cziscience.com/0a563530-3000-458e-a4d2-d549e026f326.h5ad", "https://datasets.cellxgene.cziscience.com/ccdb972d-6655-43ae-9ad8-f895bd893d8a.h5ad"]):
    adata = sc.read(f".cache/klughammer_{s_type}.h5ad", backed="r", backup_url=url)

    adata = adata[adata.obs["cell_type"]=="malignant cell"]
    adata = adata.raw.to_adata()
    adata.var_names = adata.var["feature_name"].astype(str)
    adata = clean_adata(adata)
    adata.obs[_suspension] = s_type
    adata.obs[_sample] = adata.obs["donor_id"].astype(str) + "_" + s_type
    adatas.append(adata)
adata = sc.concat(adatas)
del adatas

In [35]:
adata.var = adata.var.drop(adata.var.columns, axis=1)
adata.obs[_tissue] = "breast"
adata.obs[_project_id] = "CG-28"
adata.uns = {_count_type: "raw_counts"}

#adata.var = adata.var.drop(adata.var.columns, axis=1)
adata.obs[_technology] = adata.obs["assay"]
adata.obs = adata.obs[[_sample, _project_id, _technology, _disease, _tissue, _suspension]]
adata.write_h5ad("data/cellxgene/Klughammer_2024_breast.h5ad")

### Garcia et al. dataset

##

In [36]:
adata = sc.read(".cache/garcia.h5ad", backed="r", backup_url="https://datasets.cellxgene.cziscience.com/c613f4a1-abfe-4a2c-98d6-59748a8a234c.h5ad")

In [37]:
adata = adata[(adata.obs["cluster_label"].str.lower().str.contains("cancer", regex=False)) & (adata.obs["doublet"]=="False"), :]
adata = adata.raw.to_adata()

In [38]:
adata = clean_adata(adata)
adata.var_names = adata.var["feature_name"].astype(str)
adata.uns = {}
adata.obs[_sample] = adata.obs["patient_id"].astype(str)
adata.obs[_disease] = "HGSOC"
adata.obs[_project_id] = "CG-29"
adata.obs[_technology] = adata.obs["assay"]
adata.obs[_suspension] = "cell"
adata.obs[_tissue] = "Ovarian"

adata.uns = {_count_type: "raw_counts"}
adata.var = adata.var.drop(adata.var.columns, axis=1)

adata.obs = adata.obs[[_sample, _project_id, _technology, _disease, _tissue, _suspension]]

In [40]:
adata.write_h5ad("data/cellxgene/Garcia_2022_ovarian.h5ad")

## The single-cell lung cancer atlas (LuCA) -- extended atlas

In [5]:
adata = sc.read(".cache/salcher.h5ad", backed="r", backup_url="https://datasets.cellxgene.cziscience.com/c366b76c-b5cf-499b-ad99-84bd57f71f0f.h5ad")

In [6]:
url = "https://docs.google.com/spreadsheets/d/1bndaTtNhQe5gPzfEhmeNW_BYSW6m6cF7s4CR-XTDBh4/gviz/tq?tqx=out:csv&sheet=Overview"
metadata = pd.read_csv(url, index_col=0)
metadata = metadata[(metadata["Source"] == "CellxGene(Salcher)") & (metadata["Include"] == "Yes")]
metadata["name"] = metadata["author_last_name"] + metadata["year"].astype(str)

In [7]:
metadata

,Tissue,Article,Disease,Technology,N_samples,Source,author_last_name,year,Project ID,Include,Reason,name
lgh,,,,,,,,,,,,
Adams_2020_lung,lung,https://doi.org/10.1016/j.ccell.2022.10.008,Lung Cancer,NaN,NaN,CellxGene(Salcher),Adams,2020,CG-30,Yes,NaN,Adams2020
Chen_2020_lung,lung,https://doi.org/10.1016/j.ccell.2022.10.009,Lung Cancer,NaN,NaN,CellxGene(Salcher),Chen,2020,CG-31,Yes,NaN,Chen2020
Goveia_2020_lung,lung,https://doi.org/10.1016/j.ccell.2022.10.010,Lung Cancer,NaN,NaN,CellxGene(Salcher),Goveia,2020,CG-32,Yes,NaN,Goveia2020
Habermann_2020_lung,lung,https://doi.org/10.1016/j.ccell.2022.10.012,Lung Cancer,NaN,NaN,CellxGene(Salcher),Habermann,2020,CG-34,Yes,NaN,Habermann2020
He_2021_lung,lung,https://doi.org/10.1016/j.ccell.2022.10.014,Lung Cancer,NaN,NaN,CellxGene(Salcher),He,2021,CG-36,Yes,NaN,He2021
Madissoon_2020_lung,lung,https://doi.org/10.1016/j.ccell.2022.10.017,Lung Cancer,NaN,NaN,CellxGene(Salcher),Madissoon,2020,CG-39,Yes,NaN,Madissoon2020
Mayr_2020_lung,lung,https://doi.org/10.1016/j.ccell.2022.10.019,Lung Cancer,NaN,NaN,CellxGene(Salcher),Mayr,2020,CG-41,Yes,NaN,Mayr2020
Reyfman_2018_lung,lung,https://doi.org/10.1016/j.ccell.2022.10.020,Lung Cancer,NaN,NaN,CellxGene(Salcher),Reyfman,2018,CG-42,Yes,NaN,Reyfman2018
Travaglini_2020_lung,lung,https://doi.org/10.1016/j.ccell.2022.10.021,Lung Cancer,NaN,NaN,CellxGene(Salcher),Travaglini,2020,CG-43,Yes,NaN,Travaglini2020
Vieira_2019_lung,lung,https://doi.org/10.1016/j.ccell.2022.10.022,Lung Cancer,NaN,NaN,CellxGene(Salcher),Vieira,2019,CG-44,Yes,NaN,Vieira2019
Wu_2021_lung,lung,https://doi.org/10.1016/j.ccell.2022.10.023,Lung Cancer,GEXSCOPE technology,NaN,CellxGene(Salcher),Wu,2021,CG-45,Yes,NaN,Wu2021
Leader_2021_lung,lung,https://doi.org/10.1016/j.ccell.2022.10.025,Lung Cancer,NaN,NaN,CellxGene(Salcher),Leader,2021,CG-47,Yes,NaN,Leader2021

In [8]:
adata = adata[adata.obs["cell_type"] == "malignant cell"]
adata = adata.raw.to_adata()

In [9]:
adata.obs["name"] = adata.obs["dataset"].str.split("_").str[0] + adata.obs["dataset"].str.split("_").str[2]

In [10]:
adata = adata[adata.obs["name"].isin(metadata["name"])]

In [25]:
adata = clean_adata(adata)
adata.uns = {_count_type: "raw_counts"}
adata.var_names = adata.var["feature_name"].astype(str)
adata.var = adata.var.drop(adata.var.columns, axis=1)

In [14]:
adata.obs[["name", "assay"]].value_counts().sort_index()

name            assay
Adams2020       10x 3' v2                334
Chen2020        10x 3' v2                287
                10x 3' v3              10167
Goveia2020      10x 3' v2               1478
Habermann2020   10x 5' v1                135
He2021          10x 3' v2               4684
Leader2021      10x 3' v2               4200
                10x 3' v3                 27
                10x 5' v1                152
Madissoon2020   10x 3' v2                166
Mayr2020        Drop-seq                 122
Reyfman2018     10x 3' v2                210
Travaglini2020  Smart-seq2               449
Vieira2019      Drop-seq                  99
Wu2021          GEXSCOPE technology    32446
Name: count, dtype: int64

In [28]:
for idx, row in metadata.iterrows():
    bdata = adata[adata.obs["name"]==row["name"]].copy()
    if bdata.n_obs < 100:
        print(idx)
        continue
    bdata.var = bdata.var.drop(bdata.var.columns, axis=1)
    bdata.obs = bdata.obs[["donor_id", "assay"]]
    bdata.obs = bdata.obs.rename(columns={"donor_id": _sample, "assay": _technology})
    bdata.obs[_tissue] = "lung"
    bdata.obs[_suspension] = "cell"
    bdata.obs[_project_id] = row["Project ID"]
    bdata.obs[_disease] = "Lung Cancer"
    bdata.uns = {_count_type: "raw_counts"}
    bdata.obs = bdata.obs[[_sample, _project_id, _technology, _disease, _tissue, _suspension]]
    bdata.write_h5ad(f"data/cellxgene/{idx}.h5ad")

Vieira_2019_lung